### ISSUE TITLE
For Loop Errors

### ISSUE THREAD

**Issue by hashtagau** [HuttchDev/craft-webpme#2]
Twig seems to throw errors when trying to run WebP conversions inside for loops.

Plugin is working fine on a single image with below

```
{% for asset in item.image %}
  <img src="{{ WebP(item.image.one, {transform: 'newsThumb960x750'}) }}"
  width="{{ asset.getWidth('newsThumb960x750') }}"
  height="{{ asset.getHeight('newsThumb960x750') }}" alt="{{item.title}}" class="news-tile rounded-4">
{%  endfor %}
```

However, if I try and execute on a gallery asset loop, I get a 'type Error' (per attached file below).

Code producing the errors is:

```
{% for asset in item.photoGallery.all() %}
    <a href="{{ WebP(item.getUrl(), {transform: 'gallery1600x800'}) }}" class="glightbox3" data-glightbox data-gallery="{{item.slug}}-gallery"></a>
{%  endfor %}
```

Have also tried:
```
{% for asset in item.photoGallery.all() %}
 <a href="{{ WebP(asset.getUrl('gallery1600x800')) }}" class="glightbox3" data-glightbox data-gallery="{{item.slug}}-gallery"></a>
{%  endfor %}
```

Without the WebP plugin I would usually output these Lightbox gallery images with the following:

```
{% for asset in item.photoGallery.all() %}
<a href="{{ asset.getUrl('gallery1600x800') }}" class="glightbox3" data-glightbox data-gallery="{{item.slug}}-gallery"></a>
{%  endfor %}
```<img width="1510" alt="Screenshot 2024-05-23 at 9 13 19 AM" src="https://github.com/HuttchDev/craft-webpme/assets/26589466/2bb91634-c4bf-43c9-81e3-2e9ccfa54d38">

**Comment by HuttchDev** [comment]
Hi there,
It looks like you are passing a url / string (.getUrl()) to the WebP function rather than the actual image asset, the WebP function will return the transform url for the link:

Instead of:
` <a href="{{ WebP(asset.getUrl(), {transform: 'gallery1600x800'}) }}" class="glightbox3" data-glightbox data-gallery="{{item.slug}}-gallery"></a>`
 
 should be:
`  <a href="{{ WebP(asset, {transform: 'gallery1600x800'}) }}" class="glightbox3" data-glightbox data-gallery="{{item.slug}}-gallery"></a>`

**Comment by hashtagau** [comment]
Thanks for your help. Problem solved per you correction above.
